[package]
name = "qres_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
qres_core = { workspace = true, features = ["std"] }
serde = { workspace = true }
csv = "1.3"

[dev-dependencies]
# Dependencies for tests if needed
