[package]
name = "qres_wasm"
version = "19.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
console_error_panic_hook = "0.1"

[dependencies.qres_core]
path = "../qres_core"
default-features = false
